/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Iamm
 */
public class FrmMain extends javax.swing.JFrame {
    //Login
    model.Login mLogin=new model.Login();
    view.FrmLogin vLogin=new view.FrmLogin();
    controller.Login cLogin=null;    

    //Bus
    model.Bus mBus=new model.Bus();
    view.FrmBus vBus=new view.FrmBus();
    controller.Bus cBus=null;
    
    //Sopir
    model.Sopir mSopir=new model.Sopir();
    view.FrmSopir vSopir=new view.FrmSopir();
    controller.Sopir cSopir=null;
    
    //Kondektur
    model.Kondektur mKondektur=new model.Kondektur();
    view.FrmKondektur vKondektur=new view.FrmKondektur();
    controller.Kondektur cKondektur=null;

    /**
     * Creates new form NewMDIApplication
     */
    public FrmMain() {
        initComponents();
        this.cBus=new controller.Bus(mBus, vBus);
        this.cSopir=new controller.Sopir(mSopir, vSopir);
        this.cLogin=new controller.Login(mLogin, vLogin);
        this.cKondektur=new controller.Kondektur(mKondektur, vKondektur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuApp = new javax.swing.JMenu();
        subMenuBus = new javax.swing.JMenuItem();
        subMenuSopir = new javax.swing.JMenuItem();
        subMenuKondektur = new javax.swing.JMenuItem();
        subMenuLogin = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuApp.setMnemonic('f');
        menuApp.setText("Application");

        subMenuBus.setMnemonic('o');
        subMenuBus.setText("Data Bus");
        subMenuBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuBusActionPerformed(evt);
            }
        });
        menuApp.add(subMenuBus);

        subMenuSopir.setMnemonic('s');
        subMenuSopir.setText("Data Sopir");
        subMenuSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSopirActionPerformed(evt);
            }
        });
        menuApp.add(subMenuSopir);

        subMenuKondektur.setMnemonic('a');
        subMenuKondektur.setText("Data Kondektur");
        subMenuKondektur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuKondekturActionPerformed(evt);
            }
        });
        menuApp.add(subMenuKondektur);

        subMenuLogin.setText("Login");
        subMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuLoginActionPerformed(evt);
            }
        });
        menuApp.add(subMenuLogin);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuApp.add(exitMenuItem);

        menuBar.add(menuApp);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void subMenuBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuBusActionPerformed
        // TODO add your handling code here:
        desktopPane.remove(cBus.getView());
        desktopPane.add(cBus.getView());
        cBus.getView().setVisible(rootPaneCheckingEnabled);


    }//GEN-LAST:event_subMenuBusActionPerformed

    private void subMenuSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSopirActionPerformed
        // TODO add your handling code here:
        desktopPane.remove(cSopir.getView());
        desktopPane.add(cSopir.getView());
        cSopir.getView().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_subMenuSopirActionPerformed

    private void subMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuLoginActionPerformed
        // TODO add your handling code here:
        desktopPane.remove(cLogin.getView());
        desktopPane.add(cLogin.getView());
        cLogin.getView().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_subMenuLoginActionPerformed

    private void subMenuKondekturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuKondekturActionPerformed
        // TODO add your handling code here:
        desktopPane.remove(cKondektur.getView());
        desktopPane.add(cKondektur.getView());
        cKondektur.getView().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_subMenuKondekturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                model.Main mLogin=new model.Main();
                view.FrmMain vMain=new view.FrmMain();
                vMain.setExtendedState(vMain.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                controller.Main cMain=new controller.Main(mLogin, vMain);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu menuApp;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem subMenuBus;
    private javax.swing.JMenuItem subMenuKondektur;
    private javax.swing.JMenuItem subMenuLogin;
    private javax.swing.JMenuItem subMenuSopir;
    // End of variables declaration//GEN-END:variables

}
